replacing hardcoded node number values with variables
CircleCI-Public/server-terraform pull request #21
Opened 2020-12-02 15:59 UTC by soulchips

The number of nodes and the machine type used was hardcoded to the cluster.tf file the eks dir.

This PR replaces those values with variables so the user may tune the cluster specs to their needs from the tfvars file. defaults have been set which match our existing hardcoded values.

2020-12-02 16:42 UTC, robinsturmeit approved these changes
LGTM

2020-12-03 22:52 UTC, ryanwohara commented on eks/terraform.tfvars.template
> +# instance_type      = "m4.xlarge"
```suggestion
# instance_type      = "m4.2xlarge"
```

2020-12-03 22:53 UTC, ryanwohara commented on eks/variables.tf
> +  default     = "m4.xlarge"
```suggestion
  default     = "m4.2xlarge"
```

2020-12-03 22:54 UTC, ryanwohara approved these changes

2020-12-03 23:02 UTC, nsmith5 requested changes
Can we add [custom validation rules] to enforce the `max_capacity >= desired_capacity >= min_capacity` invariant with a good error message?

[custom validation rules]: https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules

2020-12-04 19:10 UTC, soulchips commented
> Can we add [custom validation rules](https://www.terraform.io/docs/configuration/variables.html#custom-validation-rules) to enforce the `max_capacity >= desired_capacity >= min_capacity` invariant with a good error message?

I tried this but terraform doesn't allow it at this time.
error: `The condition for variable "desired_capacity" can only refer to the variable itself "var.desired_capacity"`

I can't reference other vars in the condition

2020-12-07 16:46 UTC, nsmith5 approved these changes

2020-12-07 16:47 UTC, merged