User management for GKE
CircleCI-Public/server-terraform pull request #29
Opened 2020-12-09 16:29 UTC by robinsturmeit

This commit enables proper and secure user management in GKE by ensuring
that:

* The configuration defaults to a bastion host
* SSH keys are managed via GCP IAM mechanisms
* Process around using K8s RBAC with GCP IAM is documented

To ensure that the bastion host is actually secure, the following
changes were added when using a bastion host:

* Access to bastion can be restriced using allowed CIDR blocks
* All other access via the public internet is removed when bastion is
  used
* Documentation was updated accordingly

2020-12-09 21:21 UTC, lloydChris requested changes
should ssh access into nomad only be allowed from the bastion's IP as part of this pr: https://github.com/CircleCI-Public/server-terraform/pull/29/files#diff-88882bf861dc3cc4a3f9a35584b47be22dcf19c5a2a727fd78f7500624487bbcR131

2020-12-10 09:36 UTC, robinsturmeit commented on gke/terraform.tfvars.template
> +nomad_ssh_enabled = false
Did you use the internal IP flag to ssh into the Nomad client?

2020-12-10 14:10 UTC, lloydChris commented on gke/terraform.tfvars.template
> +nomad_ssh_enabled = false
With what key?  We chose to let GCP handle that business as per their documentation.  But that means we need to use the gcloud SSH wrapper.

2020-12-10 14:29 UTC, robinsturmeit commented on gke/terraform.tfvars.template
> +nomad_ssh_enabled = false
I commented on your PR how to do it :)
For convenience: `gcloud compute ssh robin-dev2-bastion --project nortal-server-k8s -- gcloud compute ssh robin-dev2-nomad-client-9jck --project nortal-server-k8s --internal-ip` like this.

2020-12-10 17:02 UTC, lloydChris commented on gke/terraform.tfvars.template
> +nomad_ssh_enabled = false
Hmm.  That fails for me but it looks like it is more related to permissions on my GCP account than the infra itself.

2020-12-10 18:20 UTC, robinsturmeit commented on gke/terraform.tfvars.template
> +nomad_ssh_enabled = false
Interesting. What exactly are you seeing?

2020-12-10 18:56 UTC, demophoon commented on gke/README.md
>  13. Verify that the credentials were added by running the following command:
```suggestion
14. Verify that the credentials were added by running the following command:
```

2020-12-14 17:47 UTC, lloydChris reviewed
Having trouble with permissions from the bastion

2020-12-14 17:47 UTC, lloydChris commented on gke/README.md
> +12. On the bastion, initialize gcloud: `gcloud init`
On running this command I am prompted to to use either the bastion's service account, or create a new one.  Can we add a line here to specific which one the user should select

2020-12-14 17:47 UTC, lloydChris commented on gke/README.md
> +13. Add the new GKE cluster to the Kubernetes configuration via gcloud by running the following command:
This point might be moot based on the answer to the previous comment, but I get a 403 running this command from the bastion

2020-12-14 21:22 UTC, lloydChris reviewed
A handful of comments to try and add clarity.  many are nit-picks so ignore them if you disagree

Are the RBAC settings included in backups, or will the cluster loose any custom user/role bindings?

2020-12-14 21:22 UTC, lloydChris commented on gke/managing_user_access.md
> +Roles cannot only be bound to Google Cloud IAM users. The following other subjects are supported:
```suggestion
RoleBindings are not limited to Google Cloud IAM users. The following other subjects are supported:
```

2020-12-14 21:22 UTC, lloydChris commented on gke/terraform.tfvars.template
> +# only available through the bastion host for maximum security.
```suggestion
# only available through the bastion host.
```

2020-12-14 21:22 UTC, lloydChris commented on gke/variables.tf
> +  description = "Enables SSH to Nomad clients. If enabled, use `gcloud compute ssh` to manage SSH keys. If you use a bastion host and a private endpoint, you can still connect to Nomad clients via th
I _think_ this is the case?
```suggestion
  description = "Enables SSH to Nomad clients. If enabled, use `gcloud compute ssh` to manage SSH keys. If you use a bastion host and a private endpoint, you can still connect to Nomad clients with this value set to `false` via the bastion host using their private IPs"
```

2020-12-15 14:29 UTC, lloydChris requested changes
One small name change, otherwise looks good.
Things I tested:
- I ran through the example to create a new role and binding
- Followed the instructions to get access to a cluster I did not create
- sshed into basion:
  - did k8s things there
  - sshed into nomad client from there

2020-12-15 14:29 UTC, lloydChris commented on gke/variables.tf
> +variable "private_endpoint" {
Can this be called `private_k8s_endpoint`, since that is what it controles

2020-12-15 14:51 UTC, lloydChris approved these changes

2020-12-15 15:36 UTC, nsmith5 approved these changes

2020-12-16 10:46 UTC, merged