Updating GKE instructions
CircleCI-Public/server-terraform pull request #48
Opened 2020-12-19 01:32 UTC by annabaker

- Being more specific in prereqs/assumptions. I struggled a bit on this as I am fairly new to GCP - IMO it is more helpful to spell out which roles are necessary for the default service account
- Corrected the command for gcloud in step 10, it should be --zone instead of --region

2020-12-21 09:22 UTC, robinsturmeit requested changes

2020-12-21 09:22 UTC, robinsturmeit commented on gke/README.md
>  The `--project` and `--region` flags can be omitted if `gcloud` the default values configured during initialization can be used. If you have previously used service account credentials, switch back t
Yes, you're right, it must be zone, but then this paragraph needs amending, too

2020-12-21 09:22 UTC, robinsturmeit commented on gke/README.md
> +Role Administrator, Security Admin, Project IAM Admin.
Where are these roles coming from and why are you assuming that the user will use the Compute Engine Default Service Account?

2021-03-01 20:57 UTC, nsmith5 commented
Closing as we've dropped support for the omnibus Terraform now

2021-03-01 20:57 UTC, closed without merging