RE-774: Install support-bundle plugin on bastion
CircleCI-Public/server-terraform pull request #81
Opened 2021-02-01 20:56 UTC by NiniOak

## Problem
We need to generate a support bundle in the ox-bot workflow pipeline where core services fails to deploy correctly

## Solution
Add the support-bundle plugin and download the support-bundle for the failed CCI Application deployment

2021-02-01 21:12 UTC, yugesh84 approved these changes
The bastion is gonna go away soon, and we need to figure something else out eventually (very soon), but LGTM.

2021-02-01 21:26 UTC, lloydChris approved these changes
Looks fine to me.  But I will also emphasize that the bastion will not be around soon.  I am not sure the urgency of this fix, but I would definite re-evaluate continuing to build out functionality that relies on it.

2021-02-02 17:03 UTC, rooneyshuman requested changes

2021-02-02 17:03 UTC, rooneyshuman commented on gke/private_kubernetes/extra-vms.tf
> +    "curl -LO https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.55/support-bundle_linux_amd64.tar.gz && tar xzf support-bundle_linux_amd64.tar.gz && sudo mv ./support-bundle /usr/bi
The binary name should be `kubectl-support_bundle` or `kubectl` will have issues identifying it.
```suggestion
    "curl -LO https://github.com/replicatedhq/troubleshoot/releases/download/v0.9.55/support-bundle_linux_amd64.tar.gz && tar xzf support-bundle_linux_amd64.tar.gz && sudo mv ./support-bundle /usr/bin/kubectl-support_bundle"
```

2021-02-02 17:19 UTC, merged